### config.toml
title = "CfgMgmtCamp"
baseURL = "https://cfgmgmtcamp.org"
theme = "cfgmgmtcamp"
languageCode = "ghent2027"
defaultContentLanguage = "ghent2027"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true
dataDir = "data"
assetDir = "assets"
sectionPagesMenu = "main"
buildDrafts = false
pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT = true

[params]
	dates = "1-2-3 February 2027"
	location = "Ghent, Belgium"

[pagination]
	path = "blog"
	pagerSize = 12

[outputs]
#	section = [ "HTML", "Calendar", "RSS" ]
	section = [ "HTML", "JSON" , "RSS" ]

[outputFormats]
[outputFormats.RSS]
	mediatype = "application/rss"
	baseName = "feed"
	suffix = "xml"
