### navbar
[[navbar]]
	name = "About"
	identifier = "about"
	url = "/ghent2025/about/"
	weight = -1000
[[navbar]]
	name = "Registration"
	identifier = "registration"
	url = "/ghent2025/registration/"
	weight = -900
#[[navbar]]
#	name = "FOSDEM"
#	identifier = "registration"
#	url = "https://fosdem.org/2023/schedule/track/infra_management/"
#	#url = "https://registration.cfgmgmtcamp.be/ghent/2023/"
#	weight = -900
#[[navbar]]
#	name = "CfP"
#	identifier = "cfp"
#	url = "https://cfp.cfgmgmtcamp.org/ghent2025/cfp"
#	weight = -800
[[navbar]]
	name = "Sponsors"
	identifier = "sponsors"
	url = "/ghent2025/sponsors/"
	weight = -700
[[navbar]]
	name = "Schedule"
	identifier = "schedule"
	url = "/ghent2025/schedule/"
	weight = -600
#[[navbar]]
#	name = "Social"
#	identifier = "social"
#	url = "/ghent2025/social/"
#	weight = -400
#[[navbar]]
#	name = "Speakers"
#	identifier = "speakers"
#	url = "/ghent2025/speaker/"
#	weight = -350
[[navbar]]
	name = "Location"
	identifier = "location"
	url = "/ghent2025/location/"
	weight = -500
[[navbar]]
	name = "Conduct"
	identifier = "conduct"
	url = "/ghent2025/codeofconduct/"
	weight = -300
[[navbar]]
		name = "Guide"
		identifier = "guide"
		url = "/ghent2025/guide/"
		weight = -200
#[[navbar]]
#	name = "Online Shop"
#	identifier = "shop"
#	url = "https://shop.cfgmgmtcamp.org/"
#	weight = -200
[[navbar]]
	name = "Past"
	identifier = "past"
	url = "/ghent2025/past/"
	#url = "https://archive.cfgmgmtcamp.eu/"
	weight = -100
