#!.travis.yaml
branches:
  only:
    - master

addons:
  apt:
    update: true
    packages:
      - make
      - qrencode
      - dos2unix

install:
  - export HUGOVER=0.54.0
  #- wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-32bit.tar.gz/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p}}' | xargs wget
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGOVER}/hugo_${HUGOVER}_Linux-32bit.tar.gz
  - tar xvf hugo_${HUGOVER}_Linux-32bit.tar.gz
  - rm -rf public/

script:
  - make travis
  - echo 'cfgmgmtcamp.eu' > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github_token: ${GH_TOKEN}
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: gh-pages
  on:
    branch: master

notifications:
  irc:
    channels:
      - "irc.libera.chat#cfgmgmtcamp"
    on_success: change













